### ISSUE TITLE
Missing datasets

### ISSUE THREAD

**Issue by Arsu1896** [dks2000dks/Modulation-Classification#1]
I have not found "TrainDataset.pkl" and "Clean_X_Train.npy" found in your directory. Please provide it.

**Comment by krishnasrikard** [comment]
The size of those files is very large. You can generate the files by using the code in "RadioML-Dataset/Data/SplitData.py". You can download the RadioML-Dataset from [https://www.deepsig.ai/datasets](https://www.deepsig.ai/datasets).

Sorry for the delayed reply.
Thank You.
